// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIW2DoPHI_PK9NsseazUYqX3lvCx0MGGI',
    appId: '1:612365741681:web:c68c8adcbe1841ac4a75d0',
    messagingSenderId: '612365741681',
    projectId: 'gastometro-f677e',
    authDomain: 'gastometro-f677e.firebaseapp.com',
    storageBucket: 'gastometro-f677e.appspot.com',
    measurementId: 'G-TC9HNNNRDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABNyJGibA8EHXhaeCVzPig0Ya9eW7y2Hc',
    appId: '1:612365741681:android:018688bbcfab097b4a75d0',
    messagingSenderId: '612365741681',
    projectId: 'gastometro-f677e',
    storageBucket: 'gastometro-f677e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkRqiBhH-xTfOG8JyPLlJt7bYv7Jp2GmA',
    appId: '1:612365741681:ios:8707a087692547e54a75d0',
    messagingSenderId: '612365741681',
    projectId: 'gastometro-f677e',
    storageBucket: 'gastometro-f677e.appspot.com',
    iosClientId: '612365741681-39auqb1leiha0vflibimfnudjsm1rmac.apps.googleusercontent.com',
    iosBundleId: 'com.example.despesasPessoais',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkRqiBhH-xTfOG8JyPLlJt7bYv7Jp2GmA',
    appId: '1:612365741681:ios:8707a087692547e54a75d0',
    messagingSenderId: '612365741681',
    projectId: 'gastometro-f677e',
    storageBucket: 'gastometro-f677e.appspot.com',
    iosClientId: '612365741681-39auqb1leiha0vflibimfnudjsm1rmac.apps.googleusercontent.com',
    iosBundleId: 'com.example.despesasPessoais',
  );
}
